#spring:
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/test?useSSL=false
#    username: root
#    password: 123456
#  mvc:
#    view:
#      prefix: /
#      suffix: .jsp
#  http:
#    encoding:
#      charset: UTF-8
#      force: true
#mybatis:
#  mapper-locations: classpath:mapper/*Mapper.xml
#  type-aliases-package: com.baizhi.entity



server:
  port: 8888
  context-path: /SpringBootFreeMarker
  jsp-servlet:
    init-parameters:
     development: true



#pagehelper:
#  helperDialect: mysql
#  reasonable: true
#  supportMethodsArguments: true
#  params: count=countSql

spring:
  freemarker:
    suffix: .ftl
    prefix: /
    template-loader-path: classpath:/template
    check-template-location: true
